import Container from '@/components/Container';
import Header from '@/components/Header';
import NavigationMenu from '@/components/NavigationMenu';
import { SidebarProvider } from '@/components/SidebarProvider';
import ThemeProdiver from '@/components/provider/ThemeProvider';
import type { Metadata } from 'next';
import { bebasNeue, feixen, jetbrains, oldStandard } from '../_lib/fonts';
import './globals.css';

export const metadata: Metadata = {
  title: 'Arlie',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${bebasNeue.variable} ${feixen.variable} ${oldStandard.variable} ${jetbrains.variable}`}
      >
        <SidebarProvider>
          <ThemeProdiver>
            <NavigationMenu />
            <Header />
            <Container>{children}</Container>
          </ThemeProdiver>
        </SidebarProvider>
        <div className="noise" />
      </body>
    </html>
  );
}
